project_id = "bsvsveoaihtbsteqikvp"

[functions.create-booking]
verify_jwt = false

[functions.send-booking-email]
verify_jwt = false

[functions.send-booking-sms]
verify_jwt = false

[functions.send-booking-otp]
verify_jwt = false

[functions.verify-booking-otp]
verify_jwt = false

[functions.confirm-admin-email]
verify_jwt = true

[functions.send-payment-request]
verify_jwt = false

[functions.send-payment-confirmation]
verify_jwt = false
